### ISSUE TITLE
Stop logs in terminal

### ISSUE THREAD

**Issue by rishabhmodi03** [unx21/ayame#1]
I do not want to show my chats in terminal can you please set logging whatasena or remove logging

**Comment by unx21** [comment]
> I do not want to show my chats in terminal can you please set logging whatasena or remove logging

[maybe it can help](https://github.com/Nurutomo/wabot-aq/issues/936#issuecomment-979185789)

**Comment by rishabhmodi03** [comment]
I tried it But They are still comming.
I have low programming knowledge.
